backend:
  name: git-gateway  
  branch: master
publish_mode: editorial_workflow
squash_merges: true
commit_messages:
  create: Create {{collection}} “{{slug}}”
  update: Update {{collection}} “{{slug}}”
  delete: Delete {{collection}} “{{slug}}”
  uploadMedia: Upload “{{path}}”
  deleteMedia: Delete “{{path}}”
media_folder:  "packages/gatsby-starter-docs-material-ui/static/img"
public_folder: /img
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"
display_url: https://6star.pw
logo_url:  https://6star.pw/img/logo.png
collections:
  - name: "docs"
    label: "****** Doc"
    folder: "packages/gatsby-starter-docs-material-ui/content"
    create: true
    slug: "{{category}}_{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Route", name: "route", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
