backend:
  name: git-gateway  
  branch: master

media_folder:  "packages/gatsby-starter-docs-material-ui/static/img"
public_folder: /img

display_url: https://6star.pw
logo_url:  https://6star.pw/logos/logo.png

collections:
  - name: "doc"
    label: "****** Doc"
    folder: "packages/gatsby-starter-docs-material-ui/content"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Route", name: "route", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
